# Workflow pour déployer un projet Vite sur GitHub Pages
name: Deploy Vite project to Pages

on:
  # Se déclenche sur les push vers la branche main
  push:
    branches: ["main"]

  # Permet d'exécuter manuellement depuis l'onglet Actions
  workflow_dispatch:

# Permissions nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Une seule exécution à la fois
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build et déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload du dossier dist (fichiers buildés)
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
